### ISSUE TITLE
Please release version 1.3 or new version on pypi.

### ISSUE THREAD

**Issue by marunguy** [jaraco/jaraco.compat#1]
I use CherryPy package.
Recently, Cherrypy depend on portend package.

Version 1.2 exists in pypi.python.org(or pypi.org) currently.
And Version 1.2 is installed when use 'pip install'.
Version 1.2 released in 2013 (too old ) and require 'hgtools' package on setup

Version 1.3 require 'setuptools-scm' package on setup.

I hope that version 1.3 or new version is released on pypi.

**Comment by jaraco** [comment]
1.3 released to PyPI.

**Comment by jaraco** [comment]
Looking at 1.3, it [still uses hgtools](https://github.com/jaraco/jaraco.compat/blob/1.3/setup.py#L45), but I've also released 1.4 which does not. For portend and cherrypy, however, I think this dependency is overkill and I'm going to inline the compatibility function.
